name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Clone repo with its submodules
    - uses: actions/checkout@v2
      with:
        submodules: true
    # Install python
    - name: Set up Python
      uses: actions/setup-python@v2
    # Install PlatformIO
    - name: Set up platformio
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    # Build the firmware
    - name: Build Firmware
      run: |
        pio run
    # Check the firmware
    - name: Check Firmware
      run: |
        pio check
